// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vidconfile.Data;

namespace Vidconfile.Data.Migrations
{
    [DbContext(typeof(VidconfileDBContext))]
    [Migration("20180905165449_ExtendedVideoClass")]
    partial class ExtendedVideoClass
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("Vidconfile.Data.Models.VidconfileUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("ProfilePhotoUrl");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Vidconfile.Data.Models.VidconfileUserVideo", b =>
                {
                    b.Property<Guid>("VidconfileUserId");

                    b.Property<Guid>("VideoId");

                    b.Property<Guid>("Id");

                    b.HasKey("VidconfileUserId", "VideoId");

                    b.HasIndex("VideoId");

                    b.ToTable("VidconfileUserVideo");
                });

            modelBuilder.Entity("Vidconfile.Data.Models.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("UploaderId");

                    b.HasKey("Id");

                    b.HasIndex("UploaderId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("Vidconfile.Data.Models.VidconfileUserVideo", b =>
                {
                    b.HasOne("Vidconfile.Data.Models.VidconfileUser", "VidconfileUser")
                        .WithMany("LikedVideos")
                        .HasForeignKey("VidconfileUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Vidconfile.Data.Models.Video", "Video")
                        .WithMany("LikedUsers")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Vidconfile.Data.Models.Video", b =>
                {
                    b.HasOne("Vidconfile.Data.Models.VidconfileUser", "Uploader")
                        .WithMany("UploadedVideos")
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
